# Generated by Django 5.2.15 on 2026-06-05 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0011_chunksegmentembedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ragjob',
            name='llm_base_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='ragjob',
            name='llm_model',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='ragjob',
            name='llm_provider_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('provider_type', models.CharField(choices=[('openai_compatible', 'OpenAI compatible'), ('ollama', 'Ollama'), ('llama_cpp', 'llama.cpp'), ('vllm', 'vLLM')], default='openai_compatible', max_length=32)),
                ('base_url', models.URLField(help_text='Base URL without /v1 suffix when the provider already exposes OpenAI-compatible routes.', max_length=512)),
                ('default_model', models.CharField(max_length=256)),
                ('api_key', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_status', models.CharField(blank=True, max_length=32)),
                ('last_check_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ragjob',
            name='llm_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_jobs', to='document_ai.llmprovider'),
        ),
        migrations.CreateModel(
            name='UserLLMPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rag_model', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rag_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_preferences', to='document_ai.llmprovider')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='llmprovider',
            index=models.Index(fields=['owner', 'is_active'], name='document_ai_owner_i_512301_idx'),
        ),
        migrations.AddConstraint(
            model_name='llmprovider',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_llm_provider_name_per_owner'),
        ),
    ]
