# Generated by Django 5.2.15 on 2026-06-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_ai", "0012_ragjob_llm_base_url_ragjob_llm_model_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="llmprovider",
            name="uniq_llm_provider_name_per_owner",
        ),
        migrations.RenameModel(
            old_name="LLMProvider",
            new_name="LLMEndpoint",
        ),
        migrations.RenameField(
            model_name="llmendpoint",
            old_name="provider_type",
            new_name="endpoint_type",
        ),
        migrations.RenameField(
            model_name="ragjob",
            old_name="llm_provider",
            new_name="llm_endpoint",
        ),
        migrations.RenameField(
            model_name="ragjob",
            old_name="llm_provider_name",
            new_name="llm_endpoint_name",
        ),
        migrations.RenameField(
            model_name="userllmpreference",
            old_name="rag_provider",
            new_name="rag_endpoint",
        ),
        migrations.RenameIndex(
            model_name="llmendpoint",
            new_name="document_ai_owner_i_c5ed6a_idx",
            old_name="document_ai_owner_i_512301_idx",
        ),
        migrations.AlterField(
            model_name="llmendpoint",
            name="endpoint_type",
            field=models.CharField(
                choices=[
                    ("openai_compatible", "OpenAI compatible"),
                    ("ollama", "Ollama"),
                    ("llama_cpp", "llama.cpp"),
                    ("vllm", "vLLM"),
                ],
                default="openai_compatible",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="llmendpoint",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="llm_endpoints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="llmendpoint",
            name="base_url",
            field=models.URLField(
                help_text="Base URL without /v1 suffix when the endpoint already exposes OpenAI-compatible routes.",
                max_length=512,
            ),
        ),
        migrations.AddConstraint(
            model_name="llmendpoint",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"),
                name="uniq_llm_endpoint_name_per_owner",
            ),
        ),
    ]
