# Generated by Django 5.2.15 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_ai", "0013_rename_llm_provider_to_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="ragjob",
            name="stage",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("searching", "Searching"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="queued",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="ragjob",
            name="stage_message",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
