# Generated by Django 5.2.15 on 2026-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0014_ragjob_stage_and_stage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragjob',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ragjob',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ragjob',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chunkembedding',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='documentparseresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='ragjob',
            name='stage',
            field=models.CharField(choices=[('queued', 'Queued'), ('searching', 'Searching'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='ragjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='searchjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=32),
        ),
    ]
