# Generated by Django 5.2.15 on 2026-06-09 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_ai', '0015_ragjob_cancel_reason_ragjob_cancel_requested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ragjob',
            name='answer_mode',
            field=models.CharField(choices=[('rag', 'RAG'), ('casual', 'Casual'), ('app_help', 'App help'), ('general', 'General'), ('ambiguous', 'Ambiguous')], default='rag', max_length=64),
        ),
        migrations.AddField(
            model_name='ragjob',
            name='query_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ragjob',
            name='query_intent',
            field=models.CharField(choices=[('document_question', 'Document question'), ('casual_chat', 'Casual chat'), ('app_usage', 'App usage'), ('general_question', 'General question'), ('ambiguous', 'Ambiguous')], db_index=True, default='ambiguous', max_length=64),
        ),
        migrations.AddField(
            model_name='ragjob',
            name='retrieval_query',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ragjob',
            name='retrieval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='QueryUnderstandingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(db_index=True, default='search', max_length=32)),
                ('raw_query', models.TextField()),
                ('normalized_query', models.TextField(blank=True)),
                ('semantic_query', models.TextField(blank=True)),
                ('intent', models.CharField(choices=[('document_question', 'Document question'), ('casual_chat', 'Casual chat'), ('app_usage', 'App usage'), ('general_question', 'General question'), ('ambiguous', 'Ambiguous')], db_index=True, default='ambiguous', max_length=64)),
                ('answer_mode', models.CharField(choices=[('rag', 'RAG'), ('casual', 'Casual'), ('app_help', 'App help'), ('general', 'General'), ('ambiguous', 'Ambiguous')], default='ambiguous', max_length=64)),
                ('retrieval_required', models.BooleanField(default=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='success', max_length=32)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('classification', models.JSONField(blank=True, default=dict)),
                ('query_dsl', models.JSONField(blank=True, default=dict)),
                ('orm', models.JSONField(blank=True, default=dict)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_ai_query_understanding_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ragjob',
            name='query_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rag_jobs', to='document_ai.queryunderstandinglog'),
        ),
        migrations.AddField(
            model_name='searchjob',
            name='query_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_jobs', to='document_ai.queryunderstandinglog'),
        ),
        migrations.AddIndex(
            model_name='queryunderstandinglog',
            index=models.Index(fields=['owner', 'mode', '-created_at'], name='document_ai_owner_i_41aa83_idx'),
        ),
        migrations.AddIndex(
            model_name='queryunderstandinglog',
            index=models.Index(fields=['intent', '-created_at'], name='document_ai_intent_c6e7af_idx'),
        ),
        migrations.AddIndex(
            model_name='queryunderstandinglog',
            index=models.Index(fields=['retrieval_required', '-created_at'], name='document_ai_retriev_ed87f9_idx'),
        ),
    ]
