# Generated by Django 5.2.16 on 2026-07-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_ai", "0018_performance_observability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queryunderstandinglog",
            name="intent",
            field=models.CharField(
                choices=[
                    ("document_question", "Document question"),
                    ("information", "Information"),
                    ("casual_chat", "Casual chat"),
                    ("app_usage", "App usage"),
                    ("ambiguous", "Ambiguous"),
                ],
                db_index=True,
                default="ambiguous",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="ragjob",
            name="query_intent",
            field=models.CharField(
                choices=[
                    ("document_question", "Document question"),
                    ("information", "Information"),
                    ("casual_chat", "Casual chat"),
                    ("app_usage", "App usage"),
                    ("ambiguous", "Ambiguous"),
                ],
                db_index=True,
                default="ambiguous",
                max_length=64,
            ),
        ),
    ]
