name: Pytest Unit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare env file
        run: cp .env.example .env

      - name: Build test image
        run: docker compose --profile test build test

      - name: Run unit tests
        run: docker compose --profile test run --rm test python -m pytest -m "unit"

      - name: Run integration tests
        run: docker compose --profile test run --rm test python -m pytest -m "integration"

      - name: Cleanup
        if: always()
        run: docker compose --profile test down -v --remove-orphans
